### ISSUE TITLE
Light client does not stop when respective setting disabled or app closed

### ISSUE THREAD

**Issue by veox** [walleth/walleth#93] opened 2017-11-07 16:13 UTC
Device: HTC Desire 530
OS: Android 6.0.1
Kernel: 3.10.49-perf-gd794c23
WALLETH: 0.21 (via F-Droid 1.0.1)
(anything else?)

-----

Enabling "Start Geth Light Client" in Settings, waiting a bit to verify that it's indeed started (changes the Block display in the main window) and then disabling the setting seems to leave the light client live in the background.

This can be observed mostly by WALLETH's cache continuing to grow, increased network traffic, and high battery use.

(This might be "as expected", if the "Start ..." setting is to be interpreted literally.)

However, I'd expect the background `go-ethereum` process to stop when the WALLETH app is exited and removed from the "recent screens" page (a HTC convenience for running applications). This hasn't been the case.

Observed twice: once with a sync well behind latest block, and once when having fully synced. Both times battery and mobile data consumption were attributed by Android to WALLETH.

Restarting the phone helped clear this up.

I've forgotten to try Android's "force stop" functionality, or inspecting from a terminal app like ConnectBot.

I could try and dig deeper into this, but it would be nice to know if the situation is indeed unexpected, and to get confirmation of it being observed on a non-HTC device.

**Comment by veox** [comment] 2017-11-08 10:12
What are "normal" battery/traffic use levels for when the light client is not enabled?..

I've disabled it, and restarted the phone. Upon starting WALLETH, battery/traffic use go up dramatically, to at least 5% and 5 MiB per 30 minutes.

I'm wondering, though, if this is the "normal" use level, even with light client disabled.

**Comment by ligi** [comment] 2017-11-08 13:08
Hm - you can stop the daemon by clicking on close in the corresponding notification.
Also for me it stops when changing the state in the settings.
I do not really want that the light clients stops when the app is stopped as I have some use-cases in mind where you want a running light-client but not a running app..

**Comment by veox** [comment] 2017-11-08 13:16
There is (correctly) no notification when the setting is disabled.

I'll try purging the app and re-installing to evaluate "regular" resource use.

**Comment by ligi** [comment] 2017-11-08 13:36
ACK - yea the notification shadowes if the service is running:
 no notification -> no service
 notification -> service running

If that does not work it is a but - but it should work fine - I dont see a issue there

**Comment by ligi** [comment] 2017-11-08 17:22
Closing this for now as I cannot reproduce - please feel free to reopen when it is really an error. Also happy on input on how to improve the UX here - thought having an notification is already understandable enough as I think it is a common pattern on android. Pehaps a better icon would help? To really make clear that thee is a node running  ..

**Closed** 2017-11-08 17:22 UTC
Labels: question
