### ISSUE TITLE
Transactions remain pending

### ISSUE THREAD

**Issue by ctapang** [walleth/walleth#247] opened 2018-05-12 04:26 UTC
Walleth version 0.35
Downloaded from Google Play
Samsung SM-G935T Android Version 7.0
Testing on the ropsten network

1. Our POS app displays both address and amount to pay in the QR code in Phone1;
2. Walleth picks up the correct address and amount to pay (Phone2);
3. Walleth user taps check button to send payment;
4. Walleth gets etherscan hash: 0xff8c9684933b40989f48b4efd79acc2ba01a1a66fa18a8cb1862a03aff82cd16
5. If Walleth user taps three vertical dots in upper-right corner, and selects "Open in EtherScan", etherscan web page comes up;
6. On the ropsten etherscan web page, it says:
Overview
Transaction Information {Pending}
This TxHash was found in our secondary node and should be picked up by our indexer in a short while.

It's been 8 hours, and etherscan is still showing the same pending status.
This could be an etherscan issue.

**Comment by ligi** [comment] 2018-05-12 07:59
Hi - thanks for the detailed report. Unfortunately I do not find this hash on etherscan - so I cannot look deeper. My initial guess is that the gas-price was set too low so miners did not pick it up. Gas-prices went up a but recently. In your POS-Context it might make sense to supply the gas-price with the QR-Code. Currently WallETH has no strategy of automagically adjusting the gas-price - only a link to ethgasstation so people can look up the current prices.

**Comment by ctapang** [comment] 2018-05-12 15:31
Thanks ligi. This is on the ROPSTEN network, and I think you don't support it. We are about to move our contracts to the main net, and we expect Walleth to work there.

**Comment by ligi** [comment] 2018-05-12 15:59
ropsten is supported - but you need to switch to it in the navigation menu. But I rarely use ropsten - rinkeby is much nicer for testing stuff. Ropsten had huge trouble. Btw. do you specify the network in your QR-Code?

**Comment by ctapang** [comment] 2018-05-12 16:15
No, we do not specify the network in our QR-code. Which standard format would you recommend that can do that?
We did select ropsten in the navigation menu.

**Comment by ligi** [comment] 2018-05-12 18:04
Ah now I see - the nonce is wrong - it should not be 1 - it should be 0

**Comment by ctapang** [comment] 2018-05-12 18:35
Thanks for looking into it. No, I did not edit the nonce.

**Comment by ligi** [comment] 2018-05-12 18:37
Thanks for the info - will look deeper tomorrow - currently in the country-side and cannot look to deep - will return tomorrow and look into it. Thanks for reporting and providing details!

**Comment by ligi** [comment] 2018-05-12 19:02
Hm - could not resist to try to reproduce now despite the bad internet here - but I cannot reproduce - the first nonce is 0 and not one for me. The nonce can only be one if WallETH found a transaction with a nonce  that is 0. Did you perhaps try to make another transaction before and then deleted the pending transaction? Are you able to reproduce the error? Really not sure what I can to about this currently.

**Comment by ctapang** [comment] 2018-05-12 19:05
I just remembered something:
The very first transaction had a problem because we were displaying 0x as destination address for payment, and Walleth went ahead and did the payment anyway.
I meant displaying in the QR code.

**Comment by ligi** [comment] 2018-05-12 19:15
Great - this was the missing link and explains everything - created a follow up issue #248 and will fix it for the next version. This invalid TX then had nonce 0 and was leading nonce 1 for the correct transaction - thanks so much for all the information provided - closing this now.

**Closed by ligi** 2018-05-12 19:15 UTC
Labels: evaluation needed :mag:
