### ISSUE TITLE
Wrong transactions date, all dates at time of import in walleth

### ISSUE THREAD

**Issue by soldier9945** [walleth/walleth#438] opened 2020-03-06 14:01 UTC
Hello,

When I imported my Private key for one of my adresses, the transactions were loaded up one after the other but the timestamps of the transactions were wrong: the time that was appearing on every transaction was the actual time of the update, not the time that transaction took place.

Am I doing everything right? I actually have the latest version available from the Play Store: 0.48.2.
I had this with past walleth versions, both from the Play Store and from F-Droid, but I definitively remember that this bug wasn't there until some update in the last 1 or 1.5 years.

Thank you for this otherwise great wallet app!

**Comment by ligi** [comment] 2020-03-06 15:10
Thanks for the suggestion! Still closing it as it is a duplicate of #346 - but I take this signal that I should prioritize this issue

**Closed by ligi** 2020-03-06 15:10 UTC
