### ISSUE TITLE
Please help it keeps saying could not sign transaction scaler is not in the interval not

### ISSUE THREAD

**Issue by hayjaydabtclegend** [walleth/walleth#473] opened 2020-07-25 13:04 UTC
![Screenshot_20200725-130417](https://user-images.githubusercontent.com/67201282/88457582-a2758280-ce7f-11ea-90d1-c9426b646d53.png)

**Comment by ligi** [comment] 2020-07-26 17:00
closing as it is a duplicate of #472

**Closed by ligi** 2020-07-26 17:00 UTC
