### ISSUE TITLE
Error while creating a build.

### ISSUE THREAD

**Issue by suvDroid** [walleth/walleth#185] opened 2018-02-13 07:07 UTC
```
Information:Gradle tasks [:app:generateNoGethNoFirebaseForFDroidDebugSources, :app:generateNoGethNoFirebaseForFDroidDebugAndroidTestSources, :app:mockableAndroidJar]
C:\Users\Lenovo\.gradle\caches\transforms-1\files-1.1\preference-v14-26.1.0.aar\dbdc8071c9827084d6e3ae5e74884db6\res\values\values.xml
Error:(37, 5) error: style attribute 'attr/adjustable (aka org.walleth.test:attr/adjustable)' not found.
Error:(37, 5) error: style attribute 'attr/showSeekBarValue (aka org.walleth.test:attr/showSeekBarValue)' not found.
Error:(42, 5) error: resource string/v7_preference_on (aka org.walleth.test:string/v7_preference_on) not found.
Error:(42, 5) error: resource string/v7_preference_off (aka org.walleth.test:string/v7_preference_off) not found.
Error:(59, 5) error: style attribute 'attr/switchPreferenceStyle (aka org.walleth.test:attr/switchPreferenceStyle)' not found.
Error:resource style/Preference.Category (aka org.walleth.test:style/Preference.Category) not found.
Error:resource style/Preference.CheckBoxPreference (aka org.walleth.test:style/Preference.CheckBoxPreference) not found.
Error:resource style/Preference.DialogPreference.EditTextPreference (aka org.walleth.test:style/Preference.DialogPreference.EditTextPreference) not found.
Error:resource style/Preference.DialogPreference (aka org.walleth.test:style/Preference.DialogPreference) not found.
Error:resource style/Preference.DropDown (aka org.walleth.test:style/Preference.DropDown) not found.
Error:resource style/Preference.Information (aka org.walleth.test:style/Preference.Information) not found.
Error:resource style/Preference (aka org.walleth.test:style/Preference) not found.
Error:resource style/Preference.PreferenceScreen (aka org.walleth.test:style/Preference.PreferenceScreen) not found.
Error:resource style/Preference.SeekBarPreference (aka org.walleth.test:style/Preference.SeekBarPreference) not found.
Error:resource style/Preference (aka org.walleth.test:style/Preference) not found.
Error:resource style/Preference.SwitchPreferenceCompat (aka org.walleth.test:style/Preference.SwitchPreferenceCompat) not found.
Error:resource style/PreferenceFragment (aka org.walleth.test:style/PreferenceFragment) not found.
Error:resource style/PreferenceFragmentList (aka org.walleth.test:style/PreferenceFragmentList) not found.
Error:resource style/PreferenceThemeOverlay (aka org.walleth.test:style/PreferenceThemeOverlay) not found.
E:\suv\Projects\Walleth\walleth\app\build\intermediates\incremental\mergeNoGethNoFirebaseForFDroidDebugAndroidTestResources\merged.dir\values\values.xml
Error:(116) style attribute 'attr/adjustable (aka org.walleth.test:attr/adjustable)' not found.
Error:(117) style attribute 'attr/showSeekBarValue (aka org.walleth.test:attr/showSeekBarValue)' not found.
Error:(121) resource string/v7_preference_on (aka org.walleth.test:string/v7_preference_on) not found.
Error:(122) resource string/v7_preference_off (aka org.walleth.test:string/v7_preference_off) not found.
Error:(138) style attribute 'attr/switchPreferenceStyle (aka org.walleth.test:attr/switchPreferenceStyle)' not found.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processNoGethNoFirebaseForFDroidDebugAndroidTestResources'.
> Failed to execute aapt
Information:BUILD FAILED in 1m 4s
Information:28 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by ligi** [comment] 2018-02-13 11:03
Do you build directly from master? Strange because the CI, @friedger and I can build - not sure what is happening there. Please provide more information.

**Comment by ligi** [comment] 2018-02-13 11:06
Or did you perhaps update to the build-plugin 3.0.0? This project does not yet build with 3.0.0 - if so this is a duplicate of #87 and should be closed

**Comment by suvDroid** [comment] 2018-02-13 12:23
The plugin version is 3.0.1, If this version is not supported then which version i should use and how, Please explain a bit.

**Comment by ligi** [comment] 2018-02-13 12:26
> The plugin version is 3.0.1, If this version is not supported then which version i should use

you need to use build-plugin 2.3.3 

>  and how

just do not change it - master still uses 2.3.3 - you can use Android Studio 3 - just do not click yes when it asks you to update the build-plugin

you are also very welcome to work on #87 - would love to use the new build plugin at some point - just currently I have some problems with it.

**Closed by ligi** 2018-02-13 12:26 UTC
Labels: evaluation needed, needs more info

**Comment by suvDroid** [comment] 2018-02-13 12:29
Ok thanks :), I would love to work for #87 if you have no problem in sharing up the issues with it.

**Comment by ligi** [comment] 2018-02-13 12:33
you just posted one of the issues with it ;-) 
But that might be the easier one to solve - my main blocker currently is that spoon and the plugin does not yet work with 3.X - spoon 2 should solve this but is not yet released - needs some experimentation which did not yet have priority for me

**Comment by suvDroid** [comment] 2018-02-13 12:35
ok thanks for sharing the issue. Will try to get some solution :)

**Comment by ligi** [comment] 2018-02-13 12:36
have fun!

**Comment by armandRobled** [comment] 2024-01-20 13:30
> ```
> Information:Gradle tasks [:app:generateNoGethNoFirebaseForFDroidDebugSources, :app:generateNoGethNoFirebaseForFDroidDebugAndroidTestSources, :app:mockableAndroidJar]
> C:\Users\Lenovo\.gradle\caches\transforms-1\files-1.1\preference-v14-26.1.0.aar\dbdc8071c9827084d6e3ae5e74884db6\res\values\values.xml
> Error:(37, 5) error: style attribute 'attr/adjustable (aka org.walleth.test:attr/adjustable)' not found.
> Error:(37, 5) error: style attribute 'attr/showSeekBarValue (aka org.walleth.test:attr/showSeekBarValue)' not found.
> Error:(42, 5) error: resource string/v7_preference_on (aka org.walleth.test:string/v7_preference_on) not found.
> Error:(42, 5) error: resource string/v7_preference_off (aka org.walleth.test:string/v7_preference_off) not found.
> Error:(59, 5) error: style attribute 'attr/switchPreferenceStyle (aka org.walleth.test:attr/switchPreferenceStyle)' not found.
> Error:resource style/Preference.Category (aka org.walleth.test:style/Preference.Category) not found.
> Error:resource style/Preference.CheckBoxPreference (aka org.walleth.test:style/Preference.CheckBoxPreference) not found.
> Error:resource style/Preference.DialogPreference.EditTextPreference (aka org.walleth.test:style/Preference.DialogPreference.EditTextPreference) not found.
> Error:resource style/Preference.DialogPreference (aka org.walleth.test:style/Preference.DialogPreference) not found.
> Error:resource style/Preference.DropDown (aka org.walleth.test:style/Preference.DropDown) not found.
> Error:resource style/Preference.Information (aka org.walleth.test:style/Preference.Information) not found.
> Error:resource style/Preference (aka org.walleth.test:style/Preference) not found.
> Error:resource style/Preference.PreferenceScreen (aka org.walleth.test:style/Preference.PreferenceScreen) not found.
> Error:resource style/Preference.SeekBarPreference (aka org.walleth.test:style/Preference.SeekBarPreference) not found.
> Error:resource style/Preference (aka org.walleth.test:style/Preference) not found.
> Error:resource style/Preference.SwitchPreferenceCompat (aka org.walleth.test:style/Preference.SwitchPreferenceCompat) not found.
> Error:resource style/PreferenceFragment (aka org.walleth.test:style/PreferenceFragment) not found.
> Error:resource style/PreferenceFragmentList (aka org.walleth.test:style/PreferenceFragmentList) not found.
> Error:resource style/PreferenceThemeOverlay (aka org.walleth.test:style/PreferenceThemeOverlay) not found.
> E:\suv\Projects\Walleth\walleth\app\build\intermediates\incremental\mergeNoGethNoFirebaseForFDroidDebugAndroidTestResources\merged.dir\values\values.xml
> Error:(116) style attribute 'attr/adjustable (aka org.walleth.test:attr/adjustable)' not found.
> Error:(117) style attribute 'attr/showSeekBarValue (aka org.walleth.test:attr/showSeekBarValue)' not found.
> Error:(121) resource string/v7_preference_on (aka org.walleth.test:string/v7_preference_on) not found.
> Error:(122) resource string/v7_preference_off (aka org.walleth.test:string/v7_preference_off) not found.
> Error:(138) style attribute 'attr/switchPreferenceStyle (aka org.walleth.test:attr/switchPreferenceStyle)' not found.
> Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> Error:Execution failed for task ':app:processNoGethNoFirebaseForFDroidDebugAndroidTestResources'.
> > Failed to execute aapt
> Information:BUILD FAILED in 1m 4s
> Information:28 errors
> Information:0 warnings
> Information:See complete output in console
> ```

@suvDroid
