### ISSUE TITLE
Ability to really delete Accounts

### ISSUE THREAD

**Issue by ligi** [walleth/walleth#75] opened 2017-10-26 17:21 UTC
Currently there is only soft-delete (mark as deleted) - but there are use-cases where you want to really delete an account (e.g. the key should not be on your device at all anymore)

**Comment by leafcutterant** [comment] 2018-11-09 22:29
I guess this can be closed as it's a duplicate of #250 and that issue has a better description.

**Closed** 2018-11-11 11:29 UTC
Labels: enhancement :rocket:
